export * from "./hero";
export * from "./offer";
export * from "./aboutUs";
export * from "./categories";
export * from "./testominal";
export * from "./organic";
export * from "./eco"
export * from "./meals"
export * from "./news"